export const quotesSeed = [
  {
    id: "q-014-v1",
    code: "FK-2026-014",
    clientId: "maria-zambrano",
    responsibleName: "Maria Zambrano",
    eventType: "Cumpleanos infantil",
    guestCount: 35,
    estimatedBudget: 320,
    eventLocation: "Ciudadela La Pradera, Jipijapa",
    eventDate: "2026-06-10",
    startTime: "16:00",
    endTime: "19:00",
    theme: "Spiderman con colores rojo y azul",
    requiresInvoice: false,
    commercialConditions: "Version inicial con paquete infantil basico.",
    packageId: "paquete-infantil-basico",
    customItems: [],
    version: 1,
    state: "Borrador",
    observations: "Tematica Spiderman. Version inicial.",
    isPersonalized: false,
    quoteType: "Base",
    pdfGenerated: false,
    pdfGeneratedAt: "",
    pdfFileName: "",
    calculationSnapshot: null,
  },
  {
    id: "q-014-v2",
    code: "FK-2026-014",
    clientId: "maria-zambrano",
    responsibleName: "Maria Zambrano",
    eventType: "Cumpleanos infantil",
    guestCount: 40,
    estimatedBudget: 430,
    eventLocation: "Ciudadela La Pradera, Jipijapa",
    eventDate: "2026-06-10",
    startTime: "16:00",
    endTime: "19:00",
    theme: "Spiderman con fundas personalizadas",
    requiresInvoice: false,
    commercialConditions: "Incluye transporte local y canguil personalizado. Version enviada.",
    packageId: null,
    personalizationMode: "Importada desde paquete",
    sourcePackageId: "paquete-infantil-basico",
    customItems: [
      { serviceId: "granizado", qty: 40 },
      { serviceId: "canguil", qty: 40 },
      { serviceId: "transporte-local", qty: 1 },
    ],
    version: 2,
    state: "Enviada",
    observations: "Incluye transporte local y fundas adicionales. Version enviada.",
    isPersonalized: true,
    quoteType: "Personalizada",
    pdfGenerated: true,
    pdfGeneratedAt: "2026-06-08T15:30:00.000Z",
    pdfFileName: "FK-2026-014-V2.pdf",
    calculationSnapshot: null,
  },
  {
    id: "q-015-v1",
    code: "FK-2026-015",
    clientId: "luz-valle",
    responsibleName: "Luz Valle",
    eventType: "Evento escolar",
    guestCount: 80,
    estimatedBudget: 600,
    eventLocation: "Unidad Educativa Central, Jipijapa",
    eventDate: "2026-06-14",
    startTime: "09:30",
    endTime: "13:00",
    theme: "Cierre de curso con colores institucionales",
    requiresInvoice: true,
    commercialConditions: "Evento escolar para 80 estudiantes.",
    packageId: "combo-dia-del-nino-basico",
    customItems: [],
    version: 1,
    state: "Borrador",
    observations: "Evento escolar para 80 estudiantes.",
    isPersonalized: false,
    quoteType: "Base",
    pdfGenerated: false,
    pdfGeneratedAt: "",
    pdfFileName: "",
    calculationSnapshot: null,
  },
  {
    id: "q-016-v1",
    code: "FK-2026-016",
    clientId: "carlos-mera",
    responsibleName: "Carlos Mera",
    eventType: "Evento corporativo",
    guestCount: 55,
    estimatedBudget: 750,
    eventLocation: "Salon Las Orquideas, Jipijapa",
    eventDate: "2026-06-18",
    startTime: "20:00",
    endTime: "23:30",
    theme: "Servicio nocturno elegante",
    requiresInvoice: true,
    commercialConditions: "Servicio nocturno con bartender y transporte.",
    packageId: null,
    personalizationMode: "Desde cero",
    sourcePackageId: null,
    customItems: [
      { serviceId: "photo-booth-360", qty: 1 },
      { serviceId: "personal-de-apoyo", qty: 2 },
    ],
    version: 1,
    state: "Aceptada",
    observations: "Servicio nocturno con bartender.",
    isPersonalized: true,
    quoteType: "Personalizada",
    pdfGenerated: true,
    pdfGeneratedAt: "2026-06-08T18:10:00.000Z",
    pdfFileName: "FK-2026-016-V1.pdf",
    calculationSnapshot: null,
  },
  {
    id: "q-017-v1",
    code: "FK-2026-017",
    clientId: "maria-zambrano",
    responsibleName: "Maria Zambrano",
    eventType: "Mesa dulce",
    guestCount: 25,
    estimatedBudget: 250,
    eventLocation: "Domicilio del cliente, Jipijapa",
    eventDate: "2026-06-22",
    startTime: "15:30",
    endTime: "18:30",
    theme: "Mesa dulce sencilla",
    requiresInvoice: false,
    commercialConditions: "Cliente no confirmo dentro del plazo.",
    packageId: "paquete-infantil-basico",
    customItems: [],
    version: 1,
    state: "Vencida",
    observations: "Cliente no confirmo dentro del plazo.",
    isPersonalized: false,
    quoteType: "Base",
    pdfGenerated: false,
    pdfGeneratedAt: "",
    pdfFileName: "",
    calculationSnapshot: null,
  },
];
