export const servicesSeed = [
  {
    id: "granizado-ilimitado",
    name: "Granizado ilimitado",
    type: "Servicio",
    desc: "Estacion atendida por una persona, sabores surtidos y vasos.",
    price: 120,
    state: "Activo",
    recipe: [
      { supplyId: "hielo", qty: 8 },
      { supplyId: "jarabe-azul", qty: 3 },
      { supplyId: "vasos", qty: 2 },
    ],
  },
  {
    id: "canguil-personalizado",
    name: "Canguil personalizado",
    type: "Producto",
    desc: "Fundas de canguil con etiqueta tematica y mesa de apoyo.",
    price: 45,
    state: "Activo",
    recipe: [
      { supplyId: "maiz", qty: 5 },
      { supplyId: "aceite", qty: 1 },
      { supplyId: "vasos", qty: 1 },
    ],
  },
  {
    id: "barra-cocteleria",
    name: "Barra de cocteleria",
    type: "Servicio",
    desc: "Bartender, cristaleria basica, frutas e insumos base.",
    price: 380,
    state: "Activo",
    recipe: [
      { supplyId: "ron", qty: 12 },
      { supplyId: "hielo", qty: 10 },
      { supplyId: "vasos", qty: 3 },
    ],
  },
  {
    id: "transporte-local",
    name: "Transporte local",
    type: "Servicio",
    desc: "Movilizacion dentro de Jipijapa y zonas cercanas.",
    price: 60,
    state: "Activo",
    recipe: [],
  },
  {
    id: "cupcakes-tematicos",
    name: "Cupcakes tematicos",
    type: "Producto",
    desc: "Docena decorada con motivo del evento.",
    price: 38,
    state: "Inactivo",
    recipe: [{ supplyId: "fondant", qty: 2 }],
  },
];
